### ISSUE TITLE
💡 [需求] <希望增加对BOT主动发送的图片的nsfw审查>

### ISSUE THREAD

**Issue by lux-QAQ** [avilliai/Manyana#11]
在通过功能"5张萝莉"获取~~涩图~~似乎未经过/moderate审查，发送了了较为裸露的图片。
同理在搜图功能，私法的消息中也存在同样的情况。
![1](https://github.com/avilliai/Manyana/assets/51485740/2f22f20e-edf2-4211-9a54-a54a1ce792e4)
![2](https://github.com/avilliai/Manyana/assets/51485740/869a89f9-21f5-4db0-8814-3b36eba88632)

**Comment by avilliai** [comment]
@bot {number}张{tag} 指令获取的图片基本都是这样，但在不添加"涩图" 这一关键tag时，不会出现r18级别的内容。
进行自检将降低效率，未来的更新将考虑作为可选配置项引入。

**Comment by avilliai** [comment]
针对@bot {n}张{tag} 和搜图结果添加了审核，为settings.yaml中可选配置
![image](https://github.com/avilliai/Manyana/assets/99066610/10f17bbe-a782-417c-91d6-31f8429bd17c)
