### ISSUE TITLE
ai回复问题

### ISSUE THREAD

**Issue by RSnew** [avilliai/Manyana#21]
在使用characterglm模式回复时，会得到一条报错。

manayana已经是最新版（截至2024/7/11），在更新后manayana后出现的问题，此前版本无问题
![image](https://github.com/avilliai/Manyana/assets/64447978/60c99fe5-cfd9-4c21-b18e-6258fae9e29f)

**Comment by avilliai** [comment]
确定成功更新了吗，最新版的aiReply仅有300行，而报错显示的是aiReply.py第805行，这至少是一个月前的版本

**Comment by RSnew** [comment]
我用的是manayana里自带的更新脚本进行更新的，这上面好像没有更新关于aiReply的代码emm，那我再下一个完整的包试一试
![image](https://github.com/avilliai/Manyana/assets/64447978/fede4803-956d-488e-ba7e-83e5ebf5e6e9)

**Comment by avilliai** [comment]
我需要知道你的整合包版本，如果是1.1.7，需要知道你用的是all_Requirements.rar还是常规的1.1.7(即另外两个包)

**Comment by avilliai** [comment]
> 我用的是manayana里自带的更新脚本进行更新的，这上面好像没有更新关于aiReply的代码emm，那我再下一个完整的包试一试 ![image](https://private-user-images.githubusercontent.com/64447978/347678560-fede4803-956d-488e-ba7e-83e5ebf5e6e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NzE5NTcsIm5iZiI6MTcyMDY3MTY1NywicGF0aCI6Ii82NDQ0Nzk3OC8zNDc2Nzg1NjAtZmVkZTQ4MDMtOTU2ZC00ODhlLWJhN2UtODNlNWViZjVlNmU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDA0MjA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4ZDdmZTQyOGJkODgzZjA2ZWY0NzE1YjE1YmQwZDViZjEzZWQ1YTcwMWQ3M2E2ZmQ0MWFlMGQxNmRiZmJhMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LJJh3QQe_wplT63V6-A2CsID2o20wmBKWbZSu6V3K5g)

由于不清楚你的整合包版本以及当前Manyana版本，目前我的建议是，使用release的launcher_all_requirements.rar另找一个目录重新搭建，在新的Manyana文件夹下创建temp文件夹，把旧的config文件夹下所有文件放进去，然后运行一次更新(当然是在新Manyana文件夹)

**Comment by RSnew** [comment]
昂，我也不清楚版本多少了，只知道是在2024/5/31之前的包体。我先下一个all_requirements这个版本尝试重新搭建一下，谢谢家人

**Comment by avilliai** [comment]
你之前没成功更新的原因可能是因为你的版本不能在更新出现异常时提示你，极有可能你选择的镜像源是一个失效的源。
对于你原来的旧Manyana，可以单独从仓库中下载setUp.py替换你本地对应文件，然后再运行更新脚本，并选择合适的更新源。
新的setUp.py能够反映出是否成功更新，也可以通过查看 更新日志 截止时间

**Comment by RSnew** [comment]
哦莫，好啵~我现在更新好啦嘿嘿，可以正常使用啦😙
