### ISSUE TITLE
对接[coze-discord-proxy]

### ISSUE THREAD

**Issue by avilliai** [avilliai/Manyana#4]
增加通过[cozi+Discord](https://github.com/deanxv/coze-discord-proxy#%E9%83%A8%E7%BD%B2%E5%88%B0%E7%AC%AC%E4%B8%89%E6%96%B9%E5%B9%B3%E5%8F%B0)白嫖GPT4的方案
## 视频教程
[release的cozi+discord.mp4](https://github.com/avilliai/Manyana/releases/tag/Manyana)
视频教程需要额外补充两个变量USER_ID和USER_AUTHORIZATION
环境变量配置如下
```
USER_AUTHORIZATION=XXXXXXXXXX
USER_ID=12***********1
CHANNEL_ID=119**********2
BOT_TOKEN=XXXXXXXXXX
GUILD_ID=119************9
COZE_BOT_ID=12***********6
```
- 获取USER_ID的值和获取频道id一样，开发者模式下右键用户头像即可。
- 获取USER_AUTHORIZATION请按下f12，进入浏览器开发者模式，在聊天窗口发送一条消息，然后在Network找到message，复制Authorization的值。
![image](https://github.com/avilliai/Manyana/assets/99066610/ac7ed6e0-16ca-4e66-970f-6cacbcf8563b)
没看懂的话参考[原作者](https://github.com/deanxv/coze-discord-proxy/issues/67)
## 文本教程
教程(仅为部署到DC的教程)：[Here](https://cloud.tencent.com/developer/article/2387238)
- 在上面的教程中，记录bot专属的token和id(COZE_BOT_ID),此bot为被coze托管的bot。
- 参照教程创建第二个bot(创建好就行了),并记录bot专属的token(BOT_TOKEN),此bot为我们与discord交互的bot。
- 两个bot开通对应权限(Administrator)并邀请进服务器( 过程不在此赘述上面的教程有)
- 记录服务器ID(GUILD_ID) ,和任一频道ID(CHANNEL_ID),频道内有两个bot。[参照：怎么查看我的服务器和频道id?](https://support.discord.com/hc/zh-tw/articles/206346498-%E6%88%91%E5%9C%A8%E5%93%AA%E8%A3%A1%E5%8F%AF%E4%BB%A5%E6%89%BE%E5%88%B0%E6%88%91%E7%9A%84%E7%94%A8%E6%88%B6-%E6%9C%8D%E5%8B%99%E5%99%A8-%E6%B6%88%E6%81%AFID)

[部署到Zeabur](https://github.com/deanxv/coze-discord-proxy?tab=readme-ov-file#%E9%83%A8%E7%BD%B2%E5%88%B0%E7%AC%AC%E4%B8%89%E6%96%B9%E5%B9%B3%E5%8F%B0)
设置并记录域名
![image](https://github.com/avilliai/Manyana/assets/99066610/d4ff8eec-ae06-4776-beed-b7163eff0731)

填写进Manyana/config/api.yaml，
示例：https://sff.zeabur.app/v1/chat/completions

**Comment by fansff** [comment]
感谢感谢

**Comment by avilliai** [comment]
似乎是增加了对单用户限制，按照coze-discord-proxy原作者的方案，可以注册多个账号，获取多个USER_AUTHORIZATION，用 , 隔开即可，如
```
USER_AUTHORIZATION=XXXXXXX1,XXXXXX2
USER_ID=12***********1
CHANNEL_ID=119**********2
BOT_TOKEN=XXXXXXXXXX
GUILD_ID=119************9
COZE_BOT_ID=12***********6
```
