### ISSUE TITLE
群友想写一个攻击人的功能（

### ISSUE THREAD

**Issue by man-shuo** [avilliai/Manyana#42]
这段史山出自于群友想要一个bot攻击人的功能，写完后群友还是很喜欢玩的
为了避免滥用，还是加入了概率触发和使用次数的限制
因为找不到现成的数据库，瞎写了个txt出来

def read_paragraphs_from_file(filename):
    # 读取文件中的所有段落，并以字典形式返回，键为序号，值为段落内容
    with open(filename, 'r', encoding='utf-8') as file:
        content = file.read()
        paragraphs = content.split('\n')  # 按照两个换行符拆分段落
        numbered_paragraphs = {i+1: para.strip() for i, para in enumerate(paragraphs)}  # 给每个段落加上序号
    return numbered_paragraphs
def get_random_paragraph(numbered_paragraphs):
    # 随机选择一个序号
    random_index = random.choice(list(numbered_paragraphs.keys()))
    return random_index, numbered_paragraphs[random_index]

filename = "variables.txt"

# 初始化文件内容，如果文件不存在则创建
def initialize_variables(variables_dict):
    with open(filename, 'w') as file:
        for key, value in variables_dict.items():
            file.write(f"{key}={value}\n")

# 读取变量值
def read_variables():
    variables_dict = {}
    with open(filename, 'r') as file:
        lines = file.readlines()
        for line in lines:
            key, value = line.strip().split('=')
            variables_dict[key] = value
    return variables_dict

# 读取单个变量值
def read_variable(key):
    variables = read_variables()
    return variables.get(key, None)

# 修改单个变量值
def update_variable(key, new_value):
    variables = read_variables()
    variables[key] = str(new_value)
    initialize_variables(variables)

def main(bot, logger):
    @bot.on(GroupMessage)
    async def systemiiiiii(event: GroupMessage):
       
        msg = "".join(map(str, event.message_chain[Plain]))
        # 匹配指令
        m = re.match(r'^攻击\s*(\w+)\s*$', msg.strip())
        #m = re.match(r'^攻击@\s*(\w+)\s*$', msg.strip())
        if m:
            # 取出指令中的地名
            #await bot.send(event, '成功匹配')
            name_user = m.group(1)
            filename = 'maren.txt'
            #await bot.send(event, '测试开始，开始输出结果：')
            paragraphs = read_paragraphs_from_file(filename)
            random_index, random_paragraph = get_random_paragraph(paragraphs)
            #await bot.send(event, " 序号："+str(random_index))
            await bot.send(event, "@"+str(name_user)+" "+str(random_paragraph))
    
    
    
    
    
    
    @bot.on(GroupMessage)
    async def help(event: GroupMessage):
        
        if str(event.message_chain) == "初始化":
            await bot.send(event, '正在开始初始化变量，请稍后')
            #print("收到好友消息。",f"来源：{event.member.nickname}", 获取好友昵称f"来源qq号：{event.friend.id}", 获取好友qq号f"消息内容：{event.message_chain}" # 获取消息链
            variables = {
                "cishamanshuo": 0,
                "bpname_id": 20,
                "bp_switch": 0,
                "bpname_id2":20,
                "limit_of_times":3,
                "times":0
            }
            initialize_variables(variables)
            await bot.send(event, '初始化完成')
        #await bot.send(event, '初始化完成')
        
        
        
        #指定人攻击模块
        bp_name_id=int(read_variable("bpname_id"))
        limit_of_times=int(read_variable("limit_of_times"))
        times=int(read_variable("times"))
        bp_name_id2=int(read_variable("bpname_id2"))
        bp_name_id2=bp_name_id
        bp_switch=int(read_variable("bp_switch"))
        if str(event.message_chain).startswith("测试") :
            context=str(event.message_chain)
            #await bot.send(event, str(context))
            name_id_number=re.search(r'\d+', context)
            #await bot.send(event, str(name_id_number))
            if name_id_number:
                number = int(name_id_number.group())
                update_variable("bpname_id", str(number))
            #number = int(name_id_number)
                #await bot.send(event, str(number))
        if str(event.message_chain).startswith("开始攻击") or str(event.message_chain).startswith("攻击"):
            #cishamanshuo=1
            context=str(event.message_chain)
            #await bot.send(event, str(context))
            name_id_number=re.search(r'\d+', context)
            #await bot.send(event, str(name_id_number))
            if name_id_number:
                number = int(name_id_number.group())
                update_variable("bpname_id", str(number))
                bp_name_id=int(read_variable("bpname_id"))
                if bp_name_id2 == bp_name_id and bp_switch==1:
                    await bot.send(event, 'bot从刚才就一直监听到现在了喵！')
                if bp_name_id2 != bp_name_id and bp_switch==1:
                    update_variable("times", 0)
                    await bot.send(event, 'bot收到！正在转移目标！')
                if bp_switch==0:
                    update_variable("times", 0)
                    #await bot.send(event, 'bot从刚才就一直监听到现在了喵！')
                    await bot.send(event, '收到！！即刻开始攻击！！！')
            update_variable("bp_switch", 1)
            update_variable("bpname_id2", str(number))
        if str(event.message_chain).startswith("停止攻击"):
            #cishamanshuo=0
            update_variable("bp_switch", 0)
            #global cishamanshuo
            await bot.send(event, '好的主人，这就先放他一马')
        if str(event.message_chain) == "查询攻击状态":
            bp_switch=int(read_variable("bp_switch"))
            #await bot.send(event, '攻击目标：'+str(wangruoyan))
            if bp_switch ==0:
                await bot.send(event, 'bot正在休息喵')
            if bp_switch ==1:
                await bot.send(event, '正在等待目标发言并攻击')
                
                
        if event.sender.id == bp_name_id :
            bp_switch=int(read_variable("bp_switch"))
            rnum1=random.randint(1,2)
            if bp_switch == 1:
                if '漫朔' in str(event.message_chain) or 'manshuo' in str(event.message_chain) or'漫溯' in str(event.message_chain) or'漫说' in str(event.message_chain) or'慢说' in str(event.message_chain):
                    await bot.send(event, "不可以欺负漫朔哥哥哦~~")
                else:
                    if rnum1 == 2:
                        times=int(read_variable("times"))
                        if times > limit_of_times:
                            times=times+1
                            update_variable("times", str(times))
                            limits=limit_of_times+3
                            if times < limits:
                                await bot.send(event, "攻击次数太多啦，bot要做个好孩子喵~", True)
                        else:
                            filename = 'maren.txt'
                            paragraphs = read_paragraphs_from_file(filename)
                            random_index, random_paragraph = get_random_paragraph(paragraphs)
                            await bot.send(event, str(random_paragraph), True)
                            times=times+1
                            update_variable("times", str(times))

**Comment by avilliai** [comment]
周末合并
修改建议:
1.用%主动% %被动% 区分发起人和对象，使用botname和event.sender.member_name进行对应替换。
2.不再使用txt，相关文本合并到config/groupGame.yaml，yaml文件可读性相应更强。

可以fork仓库然后提交pr，以在项目的contributors显示

**Comment by man-shuo** [comment]
该功能已经经过重写
修复了部分逻辑bug（原来是全局变量现在改为每个群具有了）
该功能没有用到发起者，所以没有使用%主动%和%被动%这两个变量。
将存储攻击人的语句和运行数据从txt转换成yaml文件，并都存储在config文件夹下。
这是做出的修改，最近会提交pr。
